---

{% if proxy_use_unaided_worker is defined and proxy_use_unaided_worker|bool %}
worker:
  sched_affinity: true
{% endif %}

resolver: resolver.d
escaper: escaper.d
server: server.d

{% if proxy_enable_syslog is defined and proxy_enable_syslog | bool %}
log:
  default:
    syslog:
      target_udp: 127.0.0.1:{{ proxy_log_udp_port }}
{% if proxy_use_cee_log_syntax is defined and proxy_use_cee_log_syntax|bool %}
      use_cee_log_syntax: true
{% else %}
      format_rfc5424:
        enterprise_id: {{ enterprise_id }}
        message_id: g3proxy
{% endif %}
{% endif %}

{% if proxy_enable_statsd is defined and proxy_enable_statsd | bool %}
stat:
  target:
    udp: 127.0.0.1:8125
  prefix: g3proxy
  emit_duration: 200ms
{% endif %}

