---

- name: "Install escaper conf for {{ escaper_name }}"
  ansible.builtin.template:
    src: "escaper.d/{{ template_name | default(escaper_name) }}.conf"
    dest: "/etc/g3proxy/{{ daemon_group }}/escaper.d/{{ escaper_name }}.conf"
    owner: root
    group: root
    mode: "0644"
  notify: Reload escaper {{ escaper_name }}
