[package]
name = "g3proxy-geoip"
version = "0.1.0"
license.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
clap.workspace = true
ip_network_table.workspace = true
g3-geoip.workspace = true

[features]
default = ["geoip"]
geoip = []

[[bin]]
name = "g3proxy-geoip"
required-features = ["geoip"]
