---

- name: Reload resolver {{ resolver_name }}
  ansible.builtin.command:
    cmd: "/usr/bin/g3proxy-ctl -G {{ daemon_group }} --control-dir /run/g3proxy reload-resolver {{ resolver_name }}"
  register: reload
  changed_when: reload.rc == 0
  when: do_reload is defined and do_reload|bool
