---

- name: "Test config file for g3proxy instance {{ daemon_group }}"
  ansible.builtin.command:
    cmd: "g3proxy -t -c /etc/g3proxy/{{ daemon_group }}/main.yaml"
  register: check
  changed_when: check.rc == 0
  listen: "Restart daemon"

- name: "Restart g3proxy instance {{ daemon_group }}"
  ansible.builtin.systemd:
    name: "g3proxy@{{ daemon_group }}.service"
    state: restarted
  listen: "Restart daemon"
