# G3Proxy Configuration without ICAP for testing
# This configuration disables ICAP to test basic proxy functionality

runtime:
  thread_number: 4

# Logging configuration
log: stdout

# Statistics configuration
stat:
  target:
    udp: 127.0.0.1:8125
  emit_duration: 2s

# Server configurations without ICAP
server:
  - name: http
    escaper: default
    type: http_proxy
    listen:
      address: "127.0.0.1:3129"
    tls_client: { }
  - name: https
    escaper: default
    type: http_proxy
    listen:
      address: "127.0.0.1:3128"
    tls_client: { }
  - name: socks
    escaper: default
    type: socks_proxy
    listen:
      address: "127.0.0.1:1081"

# DNS resolver configuration
resolver:
  - name: default
    type: c-ares

# Escaper configuration
escaper:
  - name: default
    type: direct_fixed
    resolver: default