runtime:
  thread_number: 2

# G3Proxy configuration with monitoring enabled
log: stdout

stat:
  target:
    udp: 127.0.0.1:8125
  emit_duration: 2s

auditor:
  - name: default
    protocol_inspection: { }
    tls_cert_generator: { }
    tls_ticketer: { }
    tls_stream_dump: { }
    icap_reqmod_service: icap://127.0.0.1:1344/reqmod
    icap_respmod_service: icap://127.0.0.1:1344/respmod



server:
  - name: http
    escaper: default
    auditor: default
    type: http_proxy
    listen:
      address: "127.0.0.1:3129"
    tls_client: { }
  - name: socks
    escaper: default
    type: socks_proxy
    listen:
      address: "127.0.0.1:1081"

resolver:
  - name: default
    type: c-ares

escaper:
  - name: default
    type: direct_fixed
    resolver: default
