# G3Proxy Configuration with G3ICAP Integration
# This configuration integrates G3Proxy with G3ICAP for content adaptation

runtime:
  thread_number: 4

# Logging configuration
log: stdout

# Statistics configuration
stat:
  target:
    udp: 127.0.0.1:8125
  emit_duration: 2s

# Auditor configuration with ICAP integration
auditor:
  - name: default
    protocol_inspection: { }
    tls_cert_generator: { }
    tls_ticketer: { }
    tls_stream_dump: { }
    # ICAP services for content adaptation

# Server configurations
server:
  - name: http
    escaper: default
    auditor: default
    type: http_proxy
    listen:
      address: "127.0.0.1:3129"
    tls_client: { }
  - name: https
    escaper: default
    auditor: default
    type: http_proxy
    listen:
      address: "127.0.0.1:3128"
    tls_client: { }
  - name: socks
    escaper: default
    auditor: default
    type: socks_proxy
    listen:
      address: "127.0.0.1:1081"

# DNS resolver configuration
resolver:
  - name: default
    type: c-ares

# Escaper configuration
escaper:
  - name: default
    type: direct_fixed
    resolver: default

# ICAP configuration is handled through auditor settings above
