# G3ICAP Server Configuration with G3StatsD Integration
# This configuration integrates G3ICAP with G3StatsD for comprehensive metrics collection

# Server configuration
server:
  host: "0.0.0.0"
  port: 1344
  max_connections: 1000
  connection_timeout: 30
  request_timeout: 60

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"

# Statistics configuration with G3StatsD integration
stat:
  target:
    udp: 127.0.0.1:8125
  emit_interval: 2s
  prefix: "g3icap"

# Runtime configuration
runtime:
  thread_number: 4

# Worker configuration
worker:
  thread_number: 4

# Services configuration
services:
  - name: "content-filter"
    type: "content_filter"
    enabled: true
    config:
      max_file_size: 10485760  # 10MB
      blocked_domains:
        - "malicious.com"
        - "phishing.org"
      blocked_keywords:
        - "malware"
        - "virus"
      blocked_mime_types:
        - "application/x-executable"
        - "application/x-msdownload"

  - name: "antivirus"
    type: "antivirus"
    enabled: true
    config:
      engine: "mock"
      max_file_size: 52428800  # 50MB
      scan_timeout: 30
      quarantine_enabled: true
      quarantine_path: "/tmp/g3icap-quarantine"

# Pipeline configuration
pipeline:
  stages:
    - name: "logging"
      type: "logging"
      enabled: true
    - name: "content_filter"
      type: "content_filter"
      enabled: true
    - name: "antivirus"
      type: "antivirus"
      enabled: true

# Metrics configuration
metrics:
  enabled: true
  statsd:
    enabled: true
    host: "127.0.0.1"
    port: 8125
    prefix: "g3icap"
    tags:
      service: "g3icap"
      environment: "development"
