---

{%- set conf = border_conf %}
{%- set global_user_map = {} %}
{%- set users = [] %}

{%- if border_global_users is defined %}
{%- for user in border_global_users %}
{{ global_user_map.update({user.name: user}) }}
{% endfor %}
{% endif %}

{%- if conf.users is defined %}
{%- for user in conf.users %}
{%- if user is mapping %}
{{ users.append(user) }}
{% elif user is string %}
{{ users.append(global_user_map[user]) }}
{% else %}
{% endif %}
{% endfor %}
{% endif %}

name: "{{ user_group_name }}"

{% if users is defined and users|length > 0 %}
static_users:
{{ users|to_nice_yaml }}
{% endif %}

