# G3ICAP Advanced Configuration
# Full configuration with all options for complex deployments

# Server configuration
server:
  host: "127.0.0.1"
  port: 1344
  metrics_port: 9090
  max_connections: 1000
  connection_timeout: 30
  read_timeout: 60
  write_timeout: 60

# Logging configuration
logging:
  level: "info"
  format: "json"
  output: "stdout"
  file: "/var/log/g3icap/g3icap.log"
  rotation:
    max_size: "100MB"
    max_files: 10
    compress: true

# Module configuration
modules:
  - name: "echo"
    path: "/usr/lib/g3icap/modules/libecho.so"
    version: "1.0.0"
    config:
      enabled: true
      timeout: 30
    dependencies: []
    load_timeout: 30
    max_memory: 104857600
    sandbox: true

  - name: "logging"
    path: "/usr/lib/g3icap/modules/liblogging.so"
    version: "1.0.0"
    config:
      enabled: true
      log_level: "info"
      log_requests: true
      log_responses: true
    dependencies: []
    load_timeout: 30
    max_memory: 52428800
    sandbox: true

  - name: "content_filter"
    path: "/usr/lib/g3icap/modules/libcontent_filter.so"
    version: "1.0.0"
    config:
      enabled: true
      blocked_patterns: ["malware", "virus", "trojan"]
      case_sensitive: false
      regex_mode: false
    dependencies: ["logging"]
    load_timeout: 30
    max_memory: 52428800
    sandbox: true

  - name: "antivirus"
    path: "/usr/lib/g3icap/modules/libantivirus.so"
    version: "1.0.0"
    config:
      enabled: true
      engine: "clamav"
      scan_timeout: 30
      max_file_size: 104857600
      socket_path: "/var/run/clamav/clamd.ctl"
      database_path: "/var/lib/clamav"
    dependencies: ["logging"]
    load_timeout: 30
    max_memory: 104857600
    sandbox: false

# Service configuration
services:
  - name: "echo"
    path: "/echo"
    module: "echo"
    methods: ["REQMOD", "RESPMOD", "OPTIONS"]
    preview_size: 1024
    timeout: 30
    max_connections: 100
    health_check:
      enabled: true
      interval: 10
      timeout: 5
      retries: 3
    load_balancing: "round_robin"

  - name: "logging"
    path: "/logging"
    module: "logging"
    methods: ["REQMOD", "RESPMOD"]
    preview_size: 1024
    timeout: 30
    max_connections: 50
    health_check:
      enabled: true
      interval: 15
      timeout: 5
      retries: 3
    load_balancing: "least_connections"

  - name: "content_filter"
    path: "/filter"
    module: "content_filter"
    methods: ["REQMOD", "RESPMOD"]
    preview_size: 2048
    timeout: 60
    max_connections: 200
    health_check:
      enabled: true
      interval: 20
      timeout: 10
      retries: 2
    load_balancing: "weighted_round_robin"
    weights: [1, 2, 1]
    config:
      blocked_patterns: ["malware", "virus", "trojan"]
      case_sensitive: false
      regex_mode: false

  - name: "antivirus"
    path: "/scan"
    module: "antivirus"
    methods: ["REQMOD", "RESPMOD"]
    preview_size: 10240
    timeout: 120
    max_connections: 20
    health_check:
      enabled: true
      interval: 30
      timeout: 15
      retries: 2
    load_balancing: "round_robin"
    config:
      engine: "clamav"
      scan_timeout: 30
      max_file_size: 104857600

# Pipeline configuration
pipelines:
  - name: "default"
    stages:
      - name: "logging"
        type: "logging"
        config:
          log_level: "info"
          log_requests: true
          log_responses: true
        dependencies: []
        timeout: 5
        enabled: true

      - name: "content_filter"
        type: "content_filter"
        config:
          blocked_patterns: ["malware", "virus", "trojan"]
          case_sensitive: false
          regex_mode: false
        dependencies: ["logging"]
        timeout: 10
        enabled: true

      - name: "antivirus"
        type: "antivirus"
        config:
          engine: "clamav"
          scan_timeout: 30
          max_file_size: 104857600
        dependencies: ["content_filter"]
        timeout: 60
        enabled: true

    timeout: 120
    parallel: false
    max_concurrent: 10
    fail_fast: true

  - name: "simple"
    stages:
      - name: "logging"
        type: "logging"
        config:
          log_level: "debug"
        dependencies: []
        timeout: 5
        enabled: true

    timeout: 30
    parallel: false
    max_concurrent: 5
    fail_fast: false

# Connection pooling
connection_pool:
  max_connections: 1000
  min_connections: 10
  idle_timeout: 300
  max_lifetime: 3600
  connection_timeout: 30
  keep_alive: true
  keep_alive_timeout: 60

# Memory management
memory:
  max_heap_size: 1073741824
  gc_interval: 60
  gc_threshold: 0.8
  custom_allocator: true
  memory_pools:
    - name: "small"
      size: 1024
      count: 1000
    - name: "medium"
      size: 10240
      count: 100
    - name: "large"
      size: 1048576
      count: 10

# Caching
cache:
  enabled: true
  max_size: 104857600
  ttl: 3600
  cleanup_interval: 300
  eviction_policy: "lru"
  compression: true
  compression_level: 6

# Security
security:
  enable_tls: true
  tls_cert: "/etc/g3icap/certs/server.crt"
  tls_key: "/etc/g3icap/certs/server.key"
  tls_ca: "/etc/g3icap/certs/ca.crt"
  require_client_cert: false
  cipher_suites:
    - "TLS_AES_256_GCM_SHA384"
    - "TLS_CHACHA20_POLY1305_SHA256"
    - "TLS_AES_128_GCM_SHA256"
  min_tls_version: "1.2"
  max_tls_version: "1.3"

# Rate limiting
rate_limiting:
  enabled: true
  requests_per_second: 100
  burst_size: 200
  window_size: 60
  per_client: true
  whitelist:
    - "127.0.0.1"
    - "::1"

# Monitoring and metrics
monitoring:
  prometheus:
    enabled: true
    port: 9090
    path: "/metrics"
    interval: 10

  health_check:
    enabled: true
    port: 8080
    path: "/health"
    interval: 30

  tracing:
    enabled: true
    jaeger_endpoint: "http://jaeger:14268/api/traces"
    sampling_rate: 0.1
    service_name: "g3icap"

# Statistics
stats:
  server: "127.0.0.1"
  port: 8125
  prefix: "g3icap"
  emit_interval: 10
  buffer_size: 1024
  udp_enabled: true
  tcp_enabled: false
  tags:
    daemon_group: "g3icap"
    environment: "production"
    region: "us-west-2"
