---

- hosts: "{{ group | default('g3proxy') }}"
  roles:
    - role: border-classic
  handlers:
    - ansible.builtin.import_tasks: roles/g3proxy/handlers/restart.yml
  vars:
    daemon_group: border-classic
