---

name: {{ server_name }}
type: HttpProxy

escaper: {{ escaper_name }}

listen:
  address: "[::]:{{ benchmark_https_port }}"
  backlog: 4096
listen_in_worker: true

tls_server:
  cert_pairs:
    certificate: "{{ server_name }}-{{ tls_name }}.pem"
    private_key: "{{ server_name }}-{{ tls_name }}-key.pem"

