---

name: {{ server_name }}
type: TlsStream

escaper: {{ escaper_name }}

listen:
  address: "[::]:{{ benchmark_tcp_port }}"
  backlog: 4096
  scale: 1.0

tls_server:
  cert_pairs:
    certificate: "{{ server_name }}-{{ tls_name }}.pem"
    private_key: "{{ server_name }}-{{ tls_name }}-key.pem"

