---

- name: Config escapers
  ansible.builtin.include_role:
    name: g3proxy
    tasks_from: config-escaper
    handlers_from: reload-escaper
  vars:
    template_name: "default"
    escaper_name: "ed_{{ item.key }}"
    resolver_name: "r_{{ item.key }}"
    network_name: "{{ item.key }}"
    border_conf: "{{ item.value }}"
  with_dict: "{{ border_egress_networks }}"

- name: Config auto select escaper
  ansible.builtin.include_role:
    name: g3proxy
    tasks_from: config-escaper
    handlers_from: reload-escaper
  vars:
    template_name: select
    escaper_name: select
  when: border_egress_auto_select is mapping
