---

- name: "Check if the hosts are allowed to run role {{ role_name }}"
  ansible.builtin.fail:
    msg: "This host is not allowed to run role {{ role_name }}"
  when: role_name not in allowed_roles
  tags:
    - always

- name: Upgrade rsyslog and plugins
  ansible.builtin.import_tasks: upgrade.yml
  tags:
    - never
    - upgrade
