# URI Validation Configuration
# 
# This configuration file defines URI validation settings for the G3ICAP server
# according to RFC 3507 specifications.

# Enable URI validation
enabled: true

# URI validation settings
validation:
  # Basic validation settings
  max_uri_length: 2048
  strict_mode: true
  enable_security_checks: true
  
  # ICAP-specific validation
  allowed_schemes:
    - "icap"
  
  # Default port for ICAP
  default_port: 1344
  
  # Allowed service patterns
  allowed_service_patterns:
    - "reqmod"
    - "respmod"
    - "options"
    - "preview"
    - "custom-*"  # Wildcard pattern for custom services
  
  # Reserved ports that are not allowed
  reserved_ports:
    - 0
    - 1
    - 7
    - 9
    - 11
    - 13
    - 15
    - 17
    - 19
    - 20
    - 21
    - 22
    - 23
    - 25
    - 37
    - 42
    - 43
    - 53
    - 67
    - 68
    - 69
    - 70
    - 79
    - 80
    - 88
    - 110
    - 111
    - 113
    - 119
    - 123
    - 135
    - 139
    - 143
    - 161
    - 162
    - 179
    - 389
    - 443
    - 445
    - 465
    - 514
    - 515
    - 587
    - 636
    - 993
    - 995

# URI format validation
format:
  # Allow query parameters
  allow_query_params: false
  
  # Allow fragments
  allow_fragments: false
  
  # Strict hostname validation
  strict_hostname_validation: true
  
  # Allow private IP addresses
  allow_private_ips: true
  
  # Allow localhost
  allow_localhost: true
  
  # Allow IPv6 addresses
  allow_ipv6: true

# Security settings
security:
  # Enable security checks
  enabled: true
  
  # Check for malicious patterns
  check_malicious_patterns: true
  
  # Malicious patterns to detect
  malicious_patterns:
    - ".*\\.\\./.*"  # Path traversal
    - ".*%2e%2e%2f.*"  # URL-encoded path traversal
    - ".*<script.*"  # XSS attempts
    - ".*javascript:.*"  # JavaScript injection
    - ".*data:text/html.*"  # Data URI with HTML
    - ".*vbscript:.*"  # VBScript injection
    - ".*onload=.*"  # Event handler injection
    - ".*onerror=.*"  # Event handler injection
    - ".*onclick=.*"  # Event handler injection
    - ".*eval\\(.*"  # Code injection
  
  # Blocked hostname patterns
  blocked_hostname_patterns:
    - ".*\\.local$"  # Local domains
    - ".*\\.internal$"  # Internal domains
    - ".*\\.test$"  # Test domains
    - ".*\\.dev$"  # Development domains
  
  # Blocked service patterns
  blocked_service_patterns:
    - "admin"
    - "root"
    - "system"
    - "config"
    - "debug"
    - "test"
    - "dev"

# Performance settings
performance:
  # Enable caching of validation results
  enable_caching: true
  
  # Cache size for validation results
  cache_size: 1000
  
  # Cache TTL in seconds
  cache_ttl_seconds: 300
  
  # Enable parallel validation
  enable_parallel_validation: true
  
  # Max concurrent validations
  max_concurrent_validations: 100

# Logging settings
logging:
  # Enable validation logging
  enabled: true
  
  # Log level for validation
  log_level: "info"  # debug, info, warn, error
  
  # Log valid URIs
  log_valid_uris: false
  
  # Log invalid URIs
  log_invalid_uris: true
  
  # Log validation errors
  log_validation_errors: true
  
  # Log security violations
  log_security_violations: true
  
  # Structured logging
  structured_logging: true

# Monitoring settings
monitoring:
  # Enable validation metrics
  enabled: true
  
  # Metrics collection interval in seconds
  collection_interval_seconds: 60
  
  # Track validation statistics
  track_statistics: true
  
  # Track performance metrics
  track_performance: true
  
  # Track error rates
  track_error_rates: true
  
  # Export metrics
  export_metrics: true
  
  # Metrics export formats
  export_formats:
    - "json"
    - "prometheus"
    - "statsd"

# Error handling settings
error_handling:
  # Enable detailed error messages
  detailed_errors: true
  
  # Include error context
  include_context: true
  
  # Error message format
  message_format: "detailed"  # simple, detailed, verbose
  
  # Include suggestions in error messages
  include_suggestions: true
  
  # Error message language
  language: "en"  # en, es, fr, de, etc.

# Integration settings
integration:
  # Integration with main server
  server_integration: true
  
  # Integration with input validation
  input_validation_integration: true
  
  # Integration with security module
  security_integration: true
  
  # Integration with monitoring
  monitoring_integration: true
  
  # Integration with logging
  logging_integration: true

# Compliance settings
compliance:
  # RFC 3507 compliance
  rfc3507_compliant: true
  
  # Strict RFC compliance
  strict_rfc_compliance: true
  
  # Allow extensions
  allow_extensions: true
  
  # ICAP version compliance
  icap_version: "1.0"
  
  # HTTP version compliance
  http_version: "1.1"

# Debug settings
debug:
  # Enable debug mode
  enabled: false
  
  # Verbose logging
  verbose_logging: false
  
  # Trace validation steps
  trace_validation: false
  
  # Profile performance
  profile_performance: false
  
  # Memory usage tracking
  track_memory_usage: false
