---

- name: Add G3 repo
  ansible.builtin.yum_repository:
    name: g3
    description: G3 repo
    baseurl: https://dl.cloudsmith.io/public/g3-oqh/g3-rolling/rpm/el/$releasever/$basearch
    gpgkey: https://dl.cloudsmith.io/public/g3-oqh/g3-rolling/gpg.5AC77C44E1B53433.key
    enabled: true
    proxy: "{{ g3_repo_proxy | default('_none_') }}"
